### ISSUE TITLE
Upgrade compatibility to Java 17

### ISSUE THREAD

**Issue by StitzL** [mibutec/popperfw#16]
It should become possible to use PopperFW as a library when tests are run on Java 8, 11, or 17. Currently, it is unknown if PopperFW (and its dependencies) can run on Java 17.

**Comment by mibutec** [comment]
Just tried out to build and run test latest version of Popperfw on Java 17:
- ClassForge does not support Java 17 (8 works, 17 not, can't say for now whats about the versions in between)
- PageObjects work.

ClassForge is used in BuildFramework, so guess Tests using this will also fail with Java 17. Test just using PagoObjects should be fine,
We will provide a fix making ClassForge also run on Java 17. I'll discuss this next week in Testing Guild to get timing done. Any on timing requirements beside asap?

**Comment by StitzL** [comment]
No, not that I am aware of. But I think we will have to update the dependencies as well before working on PopperFW code properly. If you like to see that done in separate tasks, I could create some - for Mockito, Javassist, JGraphT, and probably some of the others.

**Comment by team-magellan** [comment]
This is a showstopper for all Java 17 update activities  - no tests possible until this is resolved

**Comment by team-magellan** [comment]
To fix forge, look at this: https://stackoverflow.com/questions/69264559/javassist-with-jdk-17
works for me

**Comment by StitzL** [comment]
Feel free to open a PR! Just let me know if you need some help with that.

**Comment by team-magellan** [comment]
I also have a fix for PageObjectImplementation, it's trivial. Creating a PR.

**Comment by team-magellan** [comment]
PR created: https://github.com/mibutec/popperfw/pull/19

**Comment by mibutec** [comment]
merged

**Comment by team-magellan** [comment]
Please reopen since there are more failures of same kind on other places in code.

**Comment by mibutec** [comment]
When there is something not found by existing tests, please also add a reproducer test

**Comment by team-magellan** [comment]
PR created, with tests

**Comment by StitzL** [comment]
Closed by #22.
