### ISSUE TITLE
[BUG] Popper finds 'old' windows

### ISSUE THREAD

**Issue by mibutec** [mibutec/popperfw#2]
We currently have some dangling Swing tests. I have the suspicion that Popper finds "old" (not visible) windows, whereby then potentially just such a window before the current (visible) window with the same title is preferred.

Swing seems to manage the window list based on WeakReferences, so the test result depends on
- What other tests ran in the same JVM (explains why the tests run locally or in the Daily)
- Whether a GC has been run since the last test (random)

To solve one would have to org.popper.fw.jemmy.JemmyPageObjectHelper.AllWindowsSearchContextProvider.getContainer ()
not all windows, but only those where IsVisible () is true ...

**Comment by mibutec** [comment]
Is it possible to filter all not visible dialogs or may there exist usecase someone want to access not visible dialogs?

**Comment by nwwerum** [comment]
Merged the pull request...
